### ISSUE TITLE
wrong uid in "games" collection's document

### ISSUE THREAD

**Issue by changhoji** [enihsgnir/flutter-minesweeper#20]
## Expected Behavior

game 데이터의 `uid`는 "users" collection의 문서들의 `uid` 중에 존재해야 함

## Actual Behavior

"users" collection의 문서들의 `uid`가 아니라 `id`중에 존재하고 있음

## Steps to Reproduce the Problem

  1. 지뢰찾기 게임 클리어
  2. 자동으로 데이터 저장
  3. 이때 id가 invalid한 값이 들어감
  4. #11 pr을 merge하면 ranking section에 일치하는 uid를 찾지 못해 데이터를 표시하지 않음을 볼수 있음

**Comment by enihsgnir** [comment]
현재 Firestore `game` 문서의 `userId`는 Firestore `user` 문서의 `id`를 가리키는 값입니다. `user` 문서의 `uid`는 Firebase Authentication을 통해 생성된 `User`의 `uid`를 가리키고 있으므로 현재 일치하지 않는 것이 맞습니다.
#19 에 따라 `user` 문서의 `id`를 Firebase Authentication의 `uid`로 변경하게 되면 자연스레 해결될 수 있을 것 같습니다.
